### ISSUE TITLE
Add optional chaining to `window` and `document` references

### ISSUE THREAD

**Issue by FractalHQ** [themesberg/flowbite#265] opened 2022-08-30 15:40 UTC
**Describe the bug**
Flowbite breaks on the server.  It should not assume it's always on the client.

**To Reproduce**
1. Pick a modern framework with SSR
2. Try to use flowbite
3. You can't.  `window` or `document` is not defined

**Expected behavior**
It works

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by zoltanszogyenyi** [comment] 2022-09-12 12:02
Hey @FractalHQ,

Thanks for bringing this up.

Do you have any specific solution in mind?

I'm not sure I can reproduce this since I haven't yet tried a framework with SSR.

Thanks!

**Comment by FractalHQ** [comment] 2022-09-14 12:51
Usually this is as simple as optional chaining any calls to window or document, or checking if typeof window != undefined.  It would be ideal if flowbite could be rendered to a page without relying on client side browser apis because some websites opt out of client side hydration altogether when using ssr (or alternatively, when pre-rendering pages at build-time).

If it helps, I can make a simple repro repo or stackblitz.

**Comment by zoltanszogyenyi** [comment] 2022-12-07 14:43
Hey @FractalHQ,

I'm considering this update for the `v1.6.0` release. Did you manage to get some repo with an example?

**Comment by zoltanszogyenyi** [comment] 2023-01-06 20:29
Hey @FractalHQ,

Sorry for the long wait. This commit fixes SSR integration: https://github.com/themesberg/flowbite/commit/d4d09b9dcc6456f8a13553a696536f87b0bc3e22

Will be released for `v1.6.1`. Used this and it's confirmed working with Nuxt.js v3 with SSR.

**Comment by FractalHQ** [comment] 2023-01-06 21:31
Awesome!  I started a repro and was having trouble recreating the issue and forgot to follow up here -- sorry about that!  Glad it's all sorted now.

**Comment by zoltanszogyenyi** [comment] 2023-01-10 17:13
This has been fixed in the [Flowbite v1.6.1 release](https://github.com/themesberg/flowbite/releases/tag/v1.6.1).

**Closed by zoltanszogyenyi** 2023-01-10 17:13 UTC
Labels: enhancement
