### ISSUE TITLE
Expected corresponding JSX closing tag for <img>

### ISSUE THREAD

**Issue by iamsuyashpatel07** [themesberg/flowbite#511] opened 2023-03-29 07:33 UTC
**Bug Description**

Always there is closing "/" for images are recommended in HTML and on this page of [Flowbite](https://flowbite.com/docs/components/carousel/) there is no closing for images.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/59373438/228459359-f6d1df76-2ab2-4cf0-978c-26737e6512a0.png">

it can be removed by adding in every image tag like :- <img src="..." alt="..." **/**>

**Comment by Sarthak001** [comment] 2023-03-29 12:52
Its not a bug.
HTML has been based on SGML which allows tags to be omitted under certain conditions.
Since the `<img>` element cannot have any child nodes, it is defined as EMPTY and the end tag is forbidden (as it would serve no purpose).
For React : 
We always have to either close the tag or use a self-closing tag because otherwise React expects us to pass a children prop to the component.

Solution
Just use flowbite-react package and if you want to use default flowbite then you need to add a self closing tag in images.

> **Bug Description**
> 
> Always there is closing "/" for images are recommended in HTML and on this page of [Flowbite](https://flowbite.com/docs/components/carousel/) there is no closing for images.
> 
> <img alt="image" width="858" src="https://user-images.githubusercontent.com/59373438/228459359-f6d1df76-2ab2-4cf0-978c-26737e6512a0.png">
> 
> it can be removed by adding in every image tag like :- <img src="..." alt="..." **/**>

**Comment by iamsuyashpatel07** [comment] 2023-03-29 12:59
Thanks @Sarthak001

**Closed** 2023-03-29 13:00 UTC
