### ISSUE TITLE
Sidebar with Navbar keeps overlay even when closed

### ISSUE THREAD

**Issue by yiannis-gkoufas** [themesberg/flowbite#545] opened 2023-05-03 20:47 UTC
Hi, congrats for the awesome framework!
I was trying the example https://flowbite.com/docs/components/sidebar/#sidebar-with-navbar
I just copy-pasted the code within a react component, replaced `class` with `className`.
Everything was rendered just fine, but when I close the sidebar on the mobile screen it seems that it maintains the overlay over the main content. Showing the behaviour I am noticing:
![sidebar](https://user-images.githubusercontent.com/132509485/236045986-d7dcc3be-8d45-47fd-8c01-bb50b8f7ca5d.gif)

Any help would be greatly appreciated!

**Comment by yiannis-gkoufas** [comment] 2023-05-05 23:52
Just following up on this, it seems for some reason there are 2 drawer-backdrop divs created:

![image](https://user-images.githubusercontent.com/132509485/236586062-3bde9555-55af-45fc-ab60-7b9287041890.png)

**Comment by KenjiPcx** [comment] 2023-05-10 03:14
Have the same issue here

**Comment by WINBIGFOX** [comment] 2023-05-13 14:49
Have the same issue too

**Comment by RafaElZgz** [comment] 2023-05-31 11:25
I have found a possible cause and solution. The cause is that you are possibly initializing flowbite twice. Perhaps in a framework that uses components, you initialize flowbite (or the drawers) on two or more components, which are being rendered as the same time.

If it is initialized only once, in the layout for example, everything will work fine.

**Comment by deleonjulio** [comment] 2023-06-10 18:26
I have the same issue

**Comment by georgekettle** [comment] 2023-08-04 10:50
I get this same issue in rails 7 application using esbuild.

The documentation suggest that including turbo import should handle the double load issue with turbo, however I don't think it does.

https://flowbite.com/docs/getting-started/rails/#esbuild

**Comment by strid3r21** [comment] 2023-11-07 02:18
has anyone figured this out? im having the same issue in nuxt 3. weirdly it seems to work fine in dev mode, but once its deployed im experiencing the same issue.  i tried to make sure im not initializing flowbite twice anywhere like @RafaElZgz suggested, but it still doing the same thing.

**Comment by azri-cs** [comment] 2023-11-08 10:01
We have the same issue when using Laravel, turns out we initialized it in `app.js` (NPM) & `resources/views/layouts/app.blade.php` (CDN). 

How we found it:

1. Inspect the page.
2. Open the network tab, and select `JS` to filter the network.
3. Look for `flowbite.js`.

**Comment by strid3r21** [comment] 2023-11-08 10:17
> has anyone figured this out? im having the same issue in nuxt 3. weirdly it seems to work fine in dev mode, but once its deployed im experiencing the same issue. i tried to make sure im not initializing flowbite twice anywhere like @RafaElZgz suggested, but it still doing the same thing.

I think I've got it fixed on 1.8.1, the issue seemed to be I had initflowbite() initializing on 2 places. One on a default template that was on every page to open and close the side bar drawer and a 2nd on an admin page to use the tabs functionality. The solution was to just use initDrawers() on the default page and initTabs() on the admin page instead of initflowbite() in both places. 

There is also the latest version 2.0.0 that I think also solves this even if just using intiflowbite() everywhere.  But I was having some weird issues witj it where the sidebar wouldn't open consistently. Not sure if that was a 2.0.0 issue or what, but reverting back to 1.8.1 and breaking out the functions works I believe.

**Comment by zoltanszogyenyi** [comment] 2023-11-10 10:03
Hey everyone,

Fixed the double overlay issue in `v2.1.0`: https://github.com/themesberg/flowbite/releases/tag/v2.1.0

Basically, a newly added instance with the same id will override the previous instance.

Old event listeners will be removed while the new ones will be added - tested this on a local Ruby on Rails 7 project.

Would help if some of you would also cross test this!

Cheers,
Zoltan

**Closed by zoltanszogyenyi** 2023-11-10 10:03 UTC
