### ISSUE TITLE
Reload Flowbite for Ruby on Rails at turbo:frame-load 

### ISSUE THREAD

**Issue by leoplct** [themesberg/flowbite#450] opened 2023-02-16 13:32 UTC
**Describe the bug**
A flowbite component (eg. Dropdown) is present in a turbo-frame rendered after a click is not loaded because the [index.turbo.ts](https://github.com/themesberg/flowbite/blob/main/src/index.turbo.ts) library only listen for 'turbo:load' and not 'turbo:frame-load' too.

**To Reproduce**
1. Create a controller named example.rb and in its view 

```
 <%=turbo_frame_tag "example" do %>
   <!-HERE PASE DROPDOWN CODE FROM FLOWBITE https://flowbite.com/docs/components/dropdowns/. -->
<% end %>
```

2. From another page 
```
<%=turbo_frame_tag "example", src: url_for(action: :example), loading: 'lazy' do %>
      Loading...
<% end %>
```

3. After the frame is rendered, and turbo:frame-load is triggered, you will see that the dropdown is not working.

**Expected behavior**
Flowbite components working in a rended turbo frame

If you know a quick fix I could do on my side is appreciated.

**Comment by zoltanszogyenyi** [comment] 2023-03-10 11:57
Hey @leoplct,

Thanks for reporting the issue - we're providing a fix for this in `1.6.4` later today.

Also a duplicate of https://github.com/themesberg/flowbite/issues/88 so I'll be closing this for now.

Cheers,
Zoltan

**Closed by zoltanszogyenyi** 2023-03-10 11:57 UTC

**Comment by recmend** [comment] 2023-03-20 09:15
Hey @zoltanszogyenyi 

Does this capture events triggered by turbo_stream update/replace events? 1.6.4 is not working with my setup, using import map flowbite integration. 

The dropdown shows up on the page load but stops working once the frame is updated with turbo_stream.

```
For example,
render turbo_stream: turbo_stream.replace(
      '{frame}',
      partial: '"partial}',
      locals: {
         ...
      }
    )
```

**Comment by miahabdu** [comment] 2023-03-21 06:39
Running into a similar issue as @recmend when using turbo_stream.prepend for flash messages and flowbite toasts. I can dismiss a toast when the page initially loads, but cannot dismiss the toast when it's rendered through turbo_stream:

controller.rb

```
format.turbo_stream do
  flash.now[:notice] = "Action taken"
  render turbo_stream: turbo_stream.prepend("flash", partial: "layouts/flash")
  ...
end
```

_flash.html.erb
```
<% flash.each do |flash_type, message| %>
  <div id="toast-success" class="fixed flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 right-5 bottom-5 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Check icon</span>
    </div>
    <div class="ml-3 text-sm font-normal"><%= message %></div>
    <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" data-controller="dismiss" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
<% end %>
```

application.html.rb
```
<%= turbo_frame_tag id="flash" do %>
  <%= render "layouts/flash" %>
<% end %>
```

**Comment by sdhull** [comment] 2023-09-15 07:22
@zoltanszogyenyi I'm not entirely certain _why_ this is but turbo maintainers apparently _really don't want to emit an event_ when a turbo stream has completed rendering. But I had an idea: we could override the turbo stream render method, alias it, invoke it, and afterwards we could re-init flowbite. Something like this:

```
import { initFlowbite } from "flowbite";

addEventListener("turbo:before-stream-render", (event) => {
  const originalRender = event.detail.render

  event.detail.render = function (streamElement) {
    originalRender(streamElement)
    initFlowbite();
  }
})
```
I tried this, however I get `Uncaught SyntaxError: The requested module 'flowbite' does not provide an export named 'initFlowbite'` ... I'm not sure if this is because I'm using `flowbite.turbo` or because I'm using importmaps 🥴

**Comment by chrisnankervis** [comment] 2023-10-30 09:15
That fix works a treat @sdhull, thank you!

**Comment by zoltanszogyenyi** [comment] 2023-12-29 13:19
Hey @sdhull,

Really appreciate the fix! I'll have a look over it and merge it next week.

Will comment if I have anything to add to the new PR.

Cheers,
Zoltan
