### ISSUE TITLE
Carousel slide works only with at least 4 items

### ISSUE THREAD

**Issue by tnup** [themesberg/flowbite#746] opened 2023-12-06 11:32 UTC
**Describe the bug**
The carousel slides only properly with at least 4 items. 

**To Reproduce**
try the default carousel slide example from the docs (https://flowbite.com/docs/components/carousel/)

**Expected behavior**
Images to properly slide from right to left, without running through each other. 

**Desktop (please complete the following information):**
any

**Smartphone (please complete the following information):**
any

**Comment by kirkbushell** [comment] 2023-12-25 01:59
Yeah this is weird, I noticed the same thing - why is it bugging out at all?! The fact that it's reproducible on the site itself is troubling... also the fact the # of issues is immense and they don't seem to be taking them very seriously... They don't appear to be managing them, at all.

**Comment by zoltanszogyenyi** [comment] 2023-12-25 09:34
Hey @kirkbushell,

We are taking the issues very seriously and trying to manage them, Flowbite is quite a large library and ecosystem and we're only a handful of developers working on managing them as this is what we can afford at this point based on our pro sales from the main library.

Contributions are more than welcome, though we are actively looking for a software developer to help us with the main library with strong TypeScript/JavaScript and HTML/CSS knowledge. That should help us speed up the process.

As described here (https://github.com/themesberg/flowbite/pull/550#issuecomment-1868682920) I'll have a look at the carousel items bug on Wednesday as today is Christmas and tomorrow, unfortunately, I will not be at the computer.

Happy holidays!
Zoltan

**Comment by BartKieft** [comment] 2024-01-04 10:31
I added a pull request for this: [Pull request](https://github.com/themesberg/flowbite/pull/766)
Seems to be an issue with the z-index overlapping. I don't know if i checked all possible features of carousel.

**Comment by zoltanszogyenyi** [comment] 2024-01-24 14:19
Hey @BartKieft,

Merged your PR - this should solve the issue for the `v2.3` release.

**Closed** 2024-01-26 10:06 UTC
Labels: bug, v2.2.2
